FROM jenkins/jenkins:lts

# Passer en root pour installer Node.js
USER root

# Installer Node.js 18
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Revenir à l'utilisateur Jenkins
USER jenkins

# Vérifier l'installation
RUN node --version && npm --version
