global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter pour les métriques système
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  # cAdvisor pour les métriques Docker
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s

  # Application ToDo API
  - job_name: 'todo-api'
    static_configs:
      - targets: ['todo-api:3000']
    scrape_interval: 10s
    metrics_path: '/metrics'
    scrape_timeout: 5s

  # Métriques d'empreinte carbone personnalisées
  - job_name: 'carbon-footprint'
    static_configs:
      - targets: ['todo-api:3000']
    scrape_interval: 30s
    metrics_path: '/carbon-metrics'
    scrape_timeout: 10s
